# User
GET http://localhost:5000/users


###  
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "userName": "admin2345",
    "userEmail": "admin2,@example.com",
    "userPassword": "00002",
    "userContact": "0700001112"
    
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "userName": "test2UpdateUser",
    "userPassword": "00002"
}

###
PUT http://localhost:5000/users/6218dc7a90a6bba22f4a7be7
token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMThkYzdhOTBhNmJiYTIyZjRhN2JlNyIsImlhdCI6MTY0NjE0MzQzNSwiZXhwIjoxNjQ2NDAyNjM1fQ.d7Qm3OOXbfi30GFpbKv0FDubh-Jz0sIYd_7mamabGA8
Content-Type: application/json

{
    "userName": "test2UpdateUser"
}

###
DELETE  http://localhost:5000/users/6217ef4368cdc6e9c58e2c77
token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTdlZjQzNjhjZGM2ZTljNThlMmM3NyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NTczNTkwNCwiZXhwIjoxNjQ1OTk1MTA0fQ.XWs_KoH17wQUGc0qTAB84GfGsrT2weimFhhaHVT23SA
Content-Type: application/json

{
    "userName": "test2UpdateUser"
}

###  
GET http://localhost:5000/users/find/6218a5a8f08f8da777e262f8
token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMThhNWE4ZjA4ZjhkYTc3N2UyNjJmOCIsImlhdCI6MTY0NTc4MjQ4MCwiZXhwIjoxNjQ2MDQxNjgwfQ.xw7SbtSIFehlIm0JJbeoildHndbH1A5XZz80d1fF-uc
Content-Type: application/json

###

# Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "productTitle": "nike T-shirt",
    "productCategory": ["tshirt", "man"],
    "productDescription": "nike" ,
    "productImage": "test",
    "productPrice": "300",
    "productColor": "grey" ,
    "productSize": "M" 
}

###
GET http://localhost:5000/products

###
GET http://localhost:5000/products/find/621e2988e7abbe3f03f22bb3

###
DELETE  http://localhost:5000/products/621e2988e7abbe3f03f22bb3

###
PUT http://localhost:5000/products/6218a6fb7e56e22503a5f2fa
Content-Type: application/json

{
    "productTitle": "puma1"
}

###
#cart
POST  http://localhost:5000/users/cart/621e51d60d30b64cb299a412
token: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMThkYzdhOTBhNmJiYTIyZjRhN2JlNyIsImlhdCI6MTY0NjE1NDI5MCwiZXhwIjoxNjQ2NDEzNDkwfQ.P_lJkEdcwLGvGNOWrltR_d_JoP7joikdeNRvHCE5ctI
Content-Type: application/json

{
    "productTitle": "nike T-shirt",
    "productCategory": ["tshirt", "man"],
    "productDescription": "nike" ,
    "productImage": "test",
    "productPrice": "300",
    "productColor": "grey" ,
    "productSize": "M" 
}